language: node_js
node_js:
- "10.19.0"
branches:
  only:
  - master
  - firebase
before_script:
- npm install -g @angular/cli
script:
- echo "Deploy!!"
- npm install
- ng build --prod
install:
- npm install -g firebase-tools
after_success:
- firebase deploy --project hetekspel-2020 --token $FIREBASE_TOKEN
